version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "RadiatedMonkey"
    labels:
      - "scope: dependencies"
    commit-message:
      prefix: "cargo"
      include: "scope"
