[package]
name = "vex"
version = "0.1.0"
edition = "2021"
authors = ["RadiatedMonkey"]

[features]
tokio-console = ["console-subscriber"]

[dependencies]
bytes = "1.3.0"
console-subscriber = { version = "0.1.8", optional = true }
thiserror = "1.0.37"
tokio = { version = "1.23.0", features = ["net", "rt-multi-thread", "macros", "time", "sync", "signal"] }
tokio-util = "0.7.4"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
paste = "1.0.11"
rand = "0.8.5"
dashmap = "5.4.0"
parking_lot = "0.12.1"
lazy_static = "1.4.0"
flate2 = "1.0.25"
