[workspace]
members = [
    "vex-nbt",
    "vex-raknet",
    "vex-server",
    "vex-common"
]

[profile.release]
opt-level = 3
debug = false
strip = "symbols"
debug-assertions = false
overflow-checks = false
lto = "thin"
panic = "unwind"
incremental = false
codegen-units = 16
rpath = false
