[workspace]
members = [
    "pyro",
    "pyro-nbt",
    "pyro-util",
    "pyro-level"
]

[profile.release]
opt-level = 3
debug = false
strip = "symbols"
debug-assertions = false
overflow-checks = false
lto = "fat"
panic = "unwind"
incremental = false
codegen-units = 1
rpath = false
