[workspace]
resolver = "2"
members = [
    "pyro",
    "pyro-nbt",
    "pyro-util",
    "pyro-level"
]

[profile.release]
opt-level = 3
debug = true
strip = "none"  # Keep debuginfo for panic backtraces
debug-assertions = false
overflow-checks = false
lto = "thin"
panic = "unwind"
incremental = false
codegen-units = 1
rpath = false
