[package]
name = "vex"
version = "0.1.0"
edition = "2021"
authors = ["RadiatedMonkey"]

[features]
tokio-console = ["console-subscriber"]

[dependencies]
console-subscriber = { version = "0.1.8", optional = true }
thiserror = "1.0.37"
tokio = { version = "1.23.0", features = ["net", "rt-multi-thread", "macros", "time"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
