services:
  replication:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - replication-data:/data
  server:
    build: .
    depends_on:
      - replication
    ports:
      - "19132:19132"
      - "19133:19133"
    environment:
      - "RUST_BACKTRACE=1"

volumes:
  replication-data: