name: Deploy docs

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Dependency cache
      uses: Swatinem/rust-cache@v2.2.1
    
    - name: Generate documentation
      run: RUSTFLAGS='--cfg skip_leveldb' cargo doc --no-deps
      
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: target/doc
