name: Deploy docs

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Dependency cache
      uses: Swatinem/rust-cache@v2.2.1
    
    - name: Generate documentation
      run: RUSTFLAGS='--cfg skip_leveldb' cargo doc --no-deps
      
    - name: Commit generated files
      run: |
        cd target/doc
        git init
        git add -A
        git config --local user.email "actions@github.com"
        git config --local user.name "Github Actions"
        git commit -m "Deploy docs"
      
    - name: Force push to branch
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        force: true
        directory: ./target/doc
