name: CD / Docs

on:
  push:
    branches: [ "master" ]
    
  # Allow triggering manual builds
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency: 
  group: "pages-deployment"

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "--cfg skip_leveldb"

jobs:
  build:
    name: Generate docs
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5

#    - name: Install Rust
#      run: rustup toolchain install 1.90.0 --profile minimal

#    - name: Configure sccache
#      uses: actions/github-script@v7
#      with:
#        script: |
#          core.exportVariable('ACTIONS_RESULTS_URL', process.env.ACTIONS_RESULT_URL || '');
#          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
#
#    - name: Run sccache-cache
#      uses: mozilla-actions/sccache-action@v0.0.3
    
    - name: Configure Pages
      id: pages
      uses: actions/configure-pages@v5

    - name: Generate documentation
      run: cargo +1.90.0 doc --no-deps
      
    - name: Add root index
      run: |
        cd target/doc
        touch index.html
        echo "<meta http-equiv=\"refresh\" content=\"0; url=https://teampathfinders.github.io/mirai/mirai/index.html\">" > index.html

    - name: Upload docs artifact
      uses: actions/upload-pages-artifact@v4
      with:
        path: target/doc
    
  deploy:
    name: Deploy docs
    needs: build

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
