name: Continuous Integration / Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ci-${{ github.ref }}

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}
  
    steps:
    - run: rustup toolchain install 1.72.0 --profile minimal
    
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Dependency cache
      uses: Swatinem/rust-cache@v2.2.1

    - name: Build
      run: cargo +1.72.0 build
      
    - name: Test
      run: cargo +1.72.0 test -- --test-threads 1
