name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
    - run: rustup toolchain install 1.65.0 --profile minimal
    
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.2.1

    - name: Build
      run: cargo build
      
    - name: Run tests
      run: cargo test
